

name = "suggestion-oneword"
main = "src/worker.js"
compatibility_date = "2025-09-01"

d1_databases = [
  { binding = "DB", database_name = "improv_suggestions", database_id = "72c94e89-0f65-4190-8052-c14aac42a16d" }
]